src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    // #[Assert\NotBlank]
    private $title;

    #[ORM\Column(type: 'text')]
    #[Assert\NotBlank]
    private $message;

    #[ORM\Column(type: 'datetime_immutable')]
    /**
     * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    #[ORM\Column(type: 'boolean')]
    private $is_read = 0;

    #[ORM\ManyToOne(targetEntity: Profile::class, inversedBy: 'sent')]
    #[ORM\JoinColumn(nullable: false)]
    private $sender;

    #[ORM\ManyToOne(targetEntity: Profile::class, inversedBy: 'received')]
    #[ORM\JoinColumn(nullable: false)]
    private $recipient;

    #[ORM\Column(type: 'boolean')]
    private $isBasket = 0;

    #[ORM\ManyToOne(targetEntity: Announcement::class, inversedBy: 'message')]
    private $announcement;

    #[ORM\Column(type: 'boolean')]
    private $is_sender_delete = 0;

    #[ORM\Column(type: 'boolean')]
    private $is_recipient_delete = 0;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?Profile
    {
        return $this->sender;
    }

    public function setSender(?Profile $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?Profile
    {
        return $this->recipient;
    }

    public function setRecipient(?Profile $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }

    public function getIsBasket(): ?bool
    {
        return $this->isBasket;
    }

    public function setIsBasket(bool $isBasket): self
    {
        $this->isBasket = $isBasket;

        return $this;
    }

    public function getAnnouncement(): ?Announcement
    {
        return $this->announcement;
    }

    public function setAnnouncement(?Announcement $announcement): self
    {
        $this->announcement = $announcement;

        return $this;
    }

    public function getIsSenderDelete(): ?bool
    {
        return $this->is_sender_delete;
    }

    public function setIsSenderDelete(bool $is_sender_delete): self
    {
        $this->is_sender_delete = $is_sender_delete;

        return $this;
    }

    public function getIsRecipientDelete(): ?bool
    {
        return $this->is_recipient_delete;
    }

    public function setIsRecipientDelete(bool $is_recipient_delete): self
    {
        $this->is_recipient_delete = $is_recipient_delete;

        return $this;
    }

}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\Message;
use App\Entity\Profile;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                'title',
                TextType::class,
                [
                    'label' => 'Sujet',
                    "attr" => ["class" => "send__form__input"]
                ]
            )
            ->add(
                'message',
                TextareaType::class,
                [
                    "attr" => [
                        "class" => "send__form__input"
                    ]
                ]
            )
            // ->add(
            //     'recipient',
            //     EntityType::class,
            //     [
            //         "class" => Profile::class,
            //         "choice_label" => "username",
            //         "attr" => [
            //             "class" => "send__form__input"
            //         ]
            //     ]
            // )
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Form\MessageType;
use App\Form\MessageUsernameType;
use App\Repository\MessageRepository;
use App\Repository\ProfileRepository;
use Symfony\Component\Mercure\Update;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Messenger\MessageBusInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use ApiPlatform\Core\Bridge\Doctrine\EventListener\PublishMercureUpdatesListener;
use App\Entity\User;
use App\Service\MercureCookieGenerator;
use Symfony\Component\Serializer\SerializerInterface;

#[Route('/message', name: 'message_'), IsGranted("ROLE_USER")]
class MessageController extends AbstractController
{
    public function __construct(
        private EntityManagerInterface $entityManager,
        private Security $security
        )
    {
        
    }
    
    #[Route('/list', name: 'list')]
    public function list(MessageRepository $messageRepository): Response
    {        
        /** @var $user instanceof User */
        $user = $this->security->getuser();

        $recipientMessages = $messageRepository->findBy([
            'recipient' => $user->getProfile(),
            'is_recipient_delete' => 0
        ]);

        $senderMessages = $messageRepository->findBy([
            'sender' => $user->getProfile(),
            'is_sender_delete' => 0
        ]);
        
        if (!$user->getProfile()) {
            $this->addFlash('message', "Vous devez compléter votre profil pour accéder à la messagerie");
            return $this->redirectToRoute('profile_add');
        }

        return $this->render('message/list.html.twig', [
            'sender' => $senderMessages,
            'received' => $recipientMessages
        ]);
    }

    #[Route('/received', name: 'received')]
    public function received(MessageRepository $messageRepository): Response
    {
        /** @var $user instanceof User */
        $user = $this->security->getuser();
        $messages = $messageRepository->findBy([
            'recipient' => $user->getProfile(),
            'is_recipient_delete' => 0
        ]);

        // dd($message);
        // dd($profileRepository->findReceivedMessage($user->getProfile()->getId()));

        return $this->render('message/received.html.twig', [
            'messages' => $messages
        ]);
    }

    #[Route('/sent', name: 'sent')]
    public function sent(MessageRepository $messageRepository): Response
    {
        /** @var $user instanceof User */
        $user = $this->security->getuser();

        $messages = $messageRepository->findBy([
            'sender' => $user->getProfile(),
            'is_sender_delete' => 0
        ]);

        return $this->render('message/sent.html.twig', [
            'messages' => $messages
        ]);
    }

    #[Route('/contact/{username}', name: 'contact')]
    public function contact($username, Request $request, ProfileRepository $profileRepository): Response
    {
        /** @var $user instanceof User */
        $user = $this->security->getuser();

        if (!$user->getProfile()) {
            $this->addFlash('message', "Vous devez compléter votre profil pour envoyer un message");
            return $this->redirectToRoute('profile_add');
        }
        
        $message = new Message();
        $recpient = $profileRepository->findOneBy(['username' => $username]);


        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $message->setSender($user->getProfile());
            $message->setRecipient($recpient);
            $this->entityManager->persist($message);
            $this->entityManager->flush();

            $this->addFlash('success', "Votre message à bien été envoyer");
            return $this->redirectToRoute('message_list');
        }

        return $this->render('message/contact.html.twig', [
            'form' => $form->createView(),
            'username' => $username
        ]);
    }

    #[Route('/send', name: 'send')]
    public function send(
            Request $request,
            MercureCookieGenerator $cookieGenerator,
            MessageBusInterface $bus,
            ?User $user = null,
            SerializerInterface $serializer
        ): Response
    {

        /** @var $user instanceof User */
        $user = $this->security->getuser();

        if (!$user->getProfile()) {
            $this->addFlash('message', "Vous devez compléter votre profil pour envoyer un message");
            $response = $this->redirectToRoute('profile_add');

            $response->headers->set('set-cookie', $cookieGenerator->generate($this->getUser()));
            return $response;
        }
        
        $message = new Message();

        $form = $this->createForm(MessageUsernameType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $message->setSender($user->getProfile());
            $this->entityManager->persist($message);
            $this->entityManager->flush();

            $this->addFlash('success', "Votre message à bien été envoyer");
            $target = '';
            if ($user !== null) {
                $target= "http://troc-service.fr/ping/user/{$user->getProfile()->getId()}";
            }

            $update = new Update(
                "http://troc-service.fr/ping", 
                $serializer->serialize($user->getProfile(), 'json', ['groups' => 'ping']), 
                $private=false,
                $target
            );
            $bus->dispatch($update);
            return $this->redirectToRoute('message_list');
        }

        return $this->render('message/send.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    
    #[Route('/ping/{user}', name: 'ping', methods: ["POST"])]
    public function ping(MessageBusInterface $bus, ?User $user = null, SerializerInterface $serializer)
    {   
        $target = '';
        if ($user !== null) {
            $target= "http://troc-service.fr/ping/user/{$user->getProfile()->getId()}";
        }

        $update = new Update(
            "http://troc-service.fr/ping", 
            $serializer->serialize($this->getUser()->getProfile(), 'json', ['groups' => 'ping']), 
            $private=false,
            $target
        );
        $bus->dispatch($update);
        return $this->redirectToRoute('message_list');
    }

    #[Route('/basket', name: 'basket')]
    public function basket(): Response
    {
        return $this->render('message/basket.html.twig');
    }

    #[Route('/read/{id}', name: 'read')]
    public function read(Message $message): Response
    {
        $message->setIsRead(true);

        $this->entityManager->persist($message);
        $this->entityManager->flush();

        return $this->render('message/read.html.twig', compact("message"));
    }

    #[Route('/delete/{id}', name: 'delete', requirements: ['id' => '\d+'])]
    public function delete(Message $message)
    {
        /** @var $user instanceof User */
        $user = $this->security->getuser();

        // Si l'utilisateur à envoyé le message
        if ($message->getSender()->getId() == $user->getId()) {
            if ($message->getIsRecipientDelete() == true ) {
                $this->entityManager->remove($message);
                $this->entityManager->flush();

                $this->addFlash("success", "Le message a bien été supprimée");
                return $this->redirectToRoute('message_list');
            }
            else {
                $message->setIsSenderDelete(true);
                $this->entityManager->flush();
                $this->addFlash("success", "Le message a bien été supprimée");
                return $this->redirectToRoute('message_list');
            }
        }

        // Si l'utilisateur à reçu le message
        if ($message->getRecipient()->getId() == $user->getId()) {
            if ($message->getIsSenderDelete() == true) {
                $this->entityManager->remove($message);
                $this->entityManager->flush();

                $this->addFlash("success", "Le message a bien été supprimée");
                return $this->redirectToRoute('message_list');
            }
            else {
                $message->setIsRecipientDelete(true);
                $this->entityManager->flush();
                $this->addFlash("success", "Le message a bien été supprimée");
                return $this->redirectToRoute('message_list');
            }
        }
        
        return $this->redirectToRoute('message_list');
    }

}

templates/message/basket.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie !{% endblock %}

{% block body %}
    <main class="message">
        <nav class="message__nav">
            <a href="#" class="message__nav__link">Accueil</a>
            <a href="{{ path('message_received') }}" class="message__nav__link">Messages reçus</a>
            <a href="#" class="message__nav__link">Messages Envoyés</a>
        </nav>
        <h1 class="message__title">Messagerie</h1>
        <h2>Boite de réception</h2>
        <p>Vous avez reçus: {{ app.user.profile.received|length }} messages</p>
        <section>
            <table>
                <thead>
                    <tr>
                        <th>De</th>
                        <th>Sujet</th>
                        <th>Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for message in app.user.profile.received %}
                        {% if message.isRead == 0 %}
                            {% set bold = "bold" %}
                        {% else %}
                            {% set bold = "" %}
                        {% endif %}
                        <tr>
                            <td class={{bold}}>{{ message.sender.username }}</td>
                            <td class={{bold}}><a href="{{ path('message_read', {id: message.id}) }}">{{ message.title }}</a></td>
                            <td class={{bold}}>{{ message.createdAt|date('d-m-Y') }}</td>
                            <td></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </section>
        <button class="message__button">Voirs mes dossiers</button>
        <button class="message__button"><a href="{{ path('message_send') }}" class="message__button__link">Envoyé un message</a></button>
    </main>
{% endblock %}

templates/message/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contacter {{ username }}{% endblock %}

{% block body %}
<main class="contactUser">
    <button class="button__return"><i class="las la-arrow-left"></i> <a href="{{  app.request.headers.get('referer')}}" title="retour à la page précédente">retour</a></button>
    <div class="contactUser__form">  
        <h1>Contacter {{ username }}</h1>      
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <input type="submit" value="Valider">
        {{ form_end(form) }}
    </div>
</main>
{% endblock %}

templates/message/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagere de {{ app.user.profile.username }}!{% endblock %}

{% block body %}
    <main class="message" id="messagerie">
        {% include "message/partials/_nav.html.twig" %}
        <i class="las la-caret-square-right la-lg message__open" id="message-open"></i>
        <section class="message__contents">    
            <h1>Messagerie de {{ app.user.profile.username }}</h1>
            <div class="message__content">
                <h2>Résumer de ta messagerie</h2>
                <p>Vous avez reçus {{ received|length }} message{{ received|length <= 1 ? ' ' : 's'}}</p>
                <p>Vous avez envoyer {{ sender|length }} message{{ sender|length <= 1 ? ' ' : 's'}}</p>
                {# <button class="message__content__button">Voirs mes dossiers</button> #}
                <button class="message__content__button"><a href="{{ path('message_send') }}">Envoyé un message</a></button>
            </div>
        </section>
    </main>
{% endblock %}

templates/message/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Message de {{ app.user.profile.username }} !{% endblock %}

{% block body %}
    <main class="message">
    {% include "message/partials/_nav.html.twig" %}
        <i class="las la-caret-square-right la-lg message__open" id="message-open"></i>
        <section class="message__contents">    
            <h1>Messagerie de {{ app.user.profile.username }}</h1>
            <div class="message__content">
                <h2>{{ message.title }}</h2>
                <p>Message de {{ message.sender.username }}</p>
                <p>Le {{ message.createdAt|date }}</p>
                <p>{{ message.message }}</p>
                <div class="message__buttons">
                    <button><a href="{{ path('message_delete', {id: message.id}) }}"  onClick="return confirm('Confirmez la suppression');">Supprimer</a></button>
                    <button><a href="{{ path('message_contact',{'username': message.sender.username }) }}">Répondre</a></button>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/message/received.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messages envoyés de {{ app.user.profile.username }} !{% endblock %}

{% block body %}
    <main class="message">
        {% include "message/partials/_nav.html.twig" %}
        <i class="las la-caret-square-right la-lg message__open" id="message-open"></i>
        <section class="message__contents">
            <h1>Messagerie de {{ app.user.profile.username}}</h1>

            <div class="message__content">
                <h2>Boite de Réception</h2>
                <p>Vous avez reçus {{ messages|length }} message{{ messages|length > 1 ? "s" : "" }}</p>
                <table>
                    <thead>
                        <tr>
                            <th class="message__username">De</th>
                            <th class="message__subject">Sujet</th>
                            <th class="message__date">Date</th>
                            <th class="message__actions">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="message__table__body">
                        {% for message in messages %}
                            {% if message.isRead == 0 %}
                                {% set bold = "bold" %}
                            {% else %}
                                {% set bold = "" %}
                            {% endif %}
                            <tr class="message__table__body__row">
                                <td class="{{bold ~  ' message__username'}}">{{ message.sender.username }}</td>
                                <td class="{{bold ~  ' message__subject'}}">{{ message.title }}</td>
                                <td class="{{bold ~  ' message__date'}}">{{ message.createdAt|date('d-m-Y') }}</td>
                                <td class="message__actions">
                                    <a href="{{ path('message_contact', {'username': message.sender.username}) }}"><i class="las la-reply la-lg"></i></a>
                                    <a href="{{ path('message_read', {id: message.id}) }}"><i class="lab la-readme la-lg"></i></a>
                                    <a href="{{ path('message_delete', {id: message.id}) }}"  onClick="return confirm('Confirmez la suppression');"><i class="las la-trash-alt la-lg"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {# <button class="message__content__button">Voirs mes dossiers</button>
                <button class="message__content__button"><a href="{{ path('message_send') }}" class="message__content__button__link">Envoyé un message</a></button> #}
            </div>
        </section>
    </main>
{% endblock %}

templates/message/send.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contacter un autre utilisateur !{% endblock %}

{% block body %}
<main class="contactUser">
    <button class="button__return"><i class="las la-arrow-left"></i> <a href="{{  app.request.headers.get('referer')}}" title="retour à la page précédente">retour</a></button>
    <div class="contactUser__form">
        <h1>Contacter un membre de la communauté</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <input type="submit" value="Valider">
        {{ form_end(form) }}
    </div>
    {# <form action="{{ path('message_ping') }}" method="post">
        <button>ping !</button>
    </form>
    <form action="{{ path('message_ping', {user: app.user.profile.id}) }}" method="post">
        <button>ping !</button>
    </form> #}
</main>
{% endblock %}

templates/message/sent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Message envoyés de {{ app.user.profile.username }} !{% endblock %}

{% block body %}
    <main class="message">
        {% include "message/partials/_nav.html.twig" %}
        <i class="las la-caret-square-right la-lg message__open" id="message-open"></i>
        <section class="message__contents">
            <h1 class="message__contents__title">Messagerie de {{ app.user.profile.username}}</h1>

            <div class="message__content">
                <h2>Messages envoyés</h2>
                <p>Vous avez envoyés: {{ messages|length }} message{{ messages|length > 1 ? "s" : "" }}</p>
                <table>
                    <thead>
                        <tr>
                            <th class="message__username">À</th>
                            <th class="message__subject">Sujet</th>
                            <th class="message__date">Date</th>
                            <th class="message__actions">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="message__table__body">
                        {% for message in messages %}
                            <tr class="message__table__body__row">
                                <td class="message__username">{{ message.recipient.username }}</td>
                                <td class="message__subject">{{ message.title }}</td>
                                <td class="message__date">{{ message.createdAt|date('d-m-Y') }}</td>
                                <td class="message__actions">
                                    <a href="{{ path('message_read', {id: message.id}) }}"><i class="lab la-readme la-lg"></i></a>
                                    <a href="{{ path('message_delete', {id: message.id}) }}"  onClick="return confirm('Confirmez la suppression');"><i class="las la-trash-alt la-lg"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {# <button class="message__content__button">Voirs mes dossiers</button>
                <button class="message__content__button"><a href="{{ path('message_send') }}" class="message__content__button__link">Envoyé un message</a></button> #}
            </div>
        </section>
    </main>

{% endblock %}